name: CI-CD Pipeline

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MY_SECRET: ${{ secrets.AWS_ACCESS_KEY_ID  }}
      MY_VALUE: "example-value"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Print Hello World
      run: echo "Hello World"

    - name: Print Secret and Value
      run: |
        echo "My Secret: $MY_SECRET"
        echo "My Value: $MY_VALUE"

   